### ISSUE TITLE
$artifact not resolved within custom module-isolated.xml

### ISSUE THREAD

**Issue by firecreeper** [e-Spirit/firstspirit-module-gradle-plugin#1]
If I use a custom module-isolated.xml (because we must implement a legacy-editor for the TreeData Component) the variable $artifact is not resolved as described. The assembleFSM outputs a module-isolated.xml with "task &apos;:jar&apos; property &apos;archiveFileName&apos;" instead of the jar file name.

If I use the variable within a resource descriptor (copied the example from the documentation page; it doesn't matter in which area its inserted but it happens within a resource tag) it outputs the additional log information =>

Execution failed for task ':validateDescriptor'.
> File 'lib/task ':jar' property 'archiveFileName'' specified for resource '<unnamed>' in component of type 'legacy-editor' with name 'CMS_INPUT_TREESELECT' but is not found in the FSM.

**Comment by windmueller** [comment]
Thanks for reporting the issue, I just confirmed that this is indeed broken.

**Comment by windmueller** [comment]
This has been fixed in version 5.1.1. Please let us know if your issue is resolved.
