### ISSUE TITLE
Usage for On-Premises customers

### ISSUE THREAD

**Issue by koenig-dominik** [e-Spirit/firstspirit-module-gradle-plugin#2]
Currently the only available version of the plugin for on-premises customers is ancient (version 2.1.2).

The version I am referring to is available as a zip file in the [documentation](https://docs.e-spirit.com/odfs/plug-developmen/examples/modules-accessi/)

It was already [discussed here](https://community.crownpeak.com/t5/Feature-Discussions/Aktuelles-FirstSpirit-Gradle-Plugin-zur-Verf%C3%BCgung-stellen/idi-p/56798) that the source code here is of no use as the projects build process depends a lot of the closed artifactory of crownpeak, to which on-premises customers do not have access. Even when replacing all occurances of the articatory it's not possible to build, because the plugin depends on closed source dependencies.

It was also stated in the discussion that the plugin is of no use to developers as we would need cloud artifactory access.

I disagree: We host the plugin and all dependencies in our github enterprise instance and accompanied maven package registry very successfully, it's just a ancient version.

Could you append the built jar files of "annotations.jar" "firstspirit-module-gradle-plugin.jar" "fsmchecker.jar" to the [releases](https://github.com/e-Spirit/firstspirit-module-gradle-plugin/releases)?

**Comment by windmueller** [comment]
The files

- [firstspirit-module-gradle-plugin-6.2.0.jar](https://github.com/e-Spirit/firstspirit-module-gradle-plugin/releases/download/6.2.0/firstspirit-module-gradle-plugin-6.2.0.jar)
- [annotations-3.1.0.jar](https://github.com/e-Spirit/firstspirit-module-gradle-plugin/releases/download/6.2.0/annotations-3.1.0.jar)

are now attached to the [current release](https://github.com/e-Spirit/firstspirit-module-gradle-plugin/releases/tag/6.2.0). Please check if these files are sufficient to use the plugin without access to the cloud Artifactory.

The `fsmchecker.jar` should no longer be necessary.

**Comment by frequiheiko** [comment]
I would like to also get the POM file (ideally it would be included in the jar, but separate is also ok), so that Gradle can resolve the dependencies.

**Comment by windmueller** [comment]
@frequiheiko I added the POM files of the plugin for 6.2.0 and 6.2.1. The annotations.jar does not have any dependencies.

@koenig-dominik Did you find the time to check if the available files are sufficient?

**Comment by frequiheiko** [comment]
Thanks a lot, the POM is very helpful.
Now when I built a sample FSM I get the following error:
```
* What went wrong:
An exception occurred applying plugin request [id: 'de.espirit.firstspirit-module', version: '6.2.1']
> Failed to apply plugin 'de.espirit.firstspirit-module'.
   > Could not create an instance of type org.gradle.plugins.fsm.FSMPluginExtension.
      > Could not initialize class de.espirit.mavenplugins.fsmchecker.ComplianceLevel
```
It looks like the fsmchecker is also still needed, right?

**Comment by windmueller** [comment]
The class is part of the `firstspirit-module-gradle-plugin-6.2.1.jar`. Can you please post the exception?

**Comment by frequiheiko** [comment]
I cleaned the Gradle cache to force it download the POM again, now a different error occurs:
```
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve de.espirit.gradle:firstspirit-module-gradle-plugin:6.2.1.
Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://maven.rsint.net/artifactory/rs_maven_virtual/de/espirit/gradle/firstspirit-module-gradle-plugin/6.2.1/firstspirit-module-gradle-plugin-6.2.1.module'.
```

Seems the Gradle Module Metadata file is also needed.

**Comment by windmueller** [comment]
The module files are now available for the last two releases.

**Comment by frequiheiko** [comment]
Thanks a lot for the support, I was now finally able to put the FSM plugin in our Artifactory and run the build of a module successfully.

**Comment by windmueller** [comment]
Perfect, thank you very much for testing!
